### ISSUE TITLE
MMS Support

### ISSUE THREAD

**Issue by Cerothen** [wildeyedskies/mx-puppet-voipms#5]
Received this information today indicating that MMS support is happening now and it would be great if we could use it in this bridge as well
![image](https://user-images.githubusercontent.com/9008757/84815275-ccb26580-afe0-11ea-9a41-7931e0252e87.png)

**Comment by wildeyedskies** [comment]
Are there API docs for the new MMS feature?

**Comment by Cerothen** [comment]
[VoIP SMS MMS.pdf](https://github.com/zoenb/mx-puppet-voipms/files/4788835/VoIP.SMS.MMS.pdf)

I have extracted the SMS and MMS items from the API docs and put them into a PDF attached

**Comment by wildeyedskies** [comment]
Done!
